componentsVersion: 1.0.0
projects:
  lib-core:
    path: components/lib/core
    description: 'core of library'
    publish: true
  lib-storage:
    path: components/lib/storage
    description: 'storage lib'
    publish: true
  feature-login:
    path: components/feature/login
    description: 'login feature'
    publish: true
  apps-demo:
    path: apps/demo
    description: 'sample apps'
    publish: false
